FIX: AttributeError: module botocore.config' has no attribute 'load_config'
botocore.config.load_config() is removed in botocore 1.4.1<=

See: https://github.com/boto/botocore/commit/730af686e02ad7d78c4f907185fa639fa8a11874